# Generated by Django 3.2.5 on 2022-07-29 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0002_auto_20220730_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=500)),
                ('Image', models.ImageField(upload_to='media/Blogs/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=200)),
                ('Message', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='media/Customers/')),
                ('Payment_Type', models.CharField(max_length=200)),
                ('Card_no', models.CharField(max_length=200)),
                ('Card_cvs', models.CharField(max_length=200)),
                ('Card_exp', models.CharField(max_length=200)),
                ('Cash', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Shipping_Type', models.CharField(max_length=200)),
                ('Shipping_Zone', models.CharField(max_length=200)),
                ('Price', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='Image',
            field=models.ImageField(default='0', upload_to='media/Products/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Refunds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Reason', models.CharField(max_length=200)),
                ('Request_Status', models.CharField(max_length=500)),
                ('Refund_Status', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Customers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.customers')),
                ('Products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.products')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=200)),
                ('Message', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Customers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.customers')),
                ('Products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.products')),
            ],
        ),
        migrations.CreateModel(
            name='Galleries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to='media/Galleries/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.products')),
            ],
        ),
    ]
