# Generated by Django 3.2.5 on 2022-07-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0004_rename_cash_customers_paymentphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='Email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
