# Generated by Django 3.2.5 on 2022-07-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0005_alter_customers_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Title',
            new_name='Product_Name',
        ),
    ]
