# Generated by Django 3.2.5 on 2022-08-07 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0006_rename_title_products_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Shipping_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.shipping'),
            preserve_default=False,
        ),
    ]
